framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    handle_all_throwables: true
    session: true
    php_errors:
        log: true
    router:
        # Ustaw domyślny URI dla aplikacji działającej w podkatalogu
        default_uri: 'https://srv101355.seohost.com.pl/help-app-panel'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
