framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    handle_all_throwables: true
    session: true
    php_errors:
        log: true
    router:
        # Ustaw bazowy URL dla aplikacji działającej w podkatalogu
        request_context:
            base_url: /help-app-panel

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
