monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - doctrine
        - messenger

    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/doctrine_%kernel.environment%.log"
            level: debug
            channels: ["doctrine"]
        messenger:
            type: stream
            path: "%kernel.logs_dir%/messenger_%kernel.environment%.log"
            level: info
            channels: ["messenger"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/deprecation_%kernel.environment%.log"
            level: debug
            channels: ["deprecation"]
